# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s-I6tTm2btVn7Cjst-wD9wDUKu74MF75
"""

import random
print('whats your name ')
a=str(input())
print('\n')
print("hello "+a+", Welcome to expert system of documents")
print('\n')
print('what you want me to do')
ques=['identify documents','Identify documents','classify documents','Classify Documents']
s=str(input())
print('\n')
type=0
if ques[0] in s or ques[1] in s:
    type=1
elif ques[2] in s or ques[3] in s:
    type=2
if(type==1):
    print('enter the file name along with extension: ')
    fn=str(input())
    l=len(fn)
    for i in range(0,l):
        if(fn[i]=='.'):
            j=i
    if(fn[(j+1):]=='exe'):
        print('your file is a extension file')
    elif(fn[(j+1):]=='doc' or fn[(j+1):]=='docx'):
        print('your file is a MS Word file')
    elif(fn[(j+1):]=='html'):
      print('your file is a html file')
    elif(fn[(j+1):]=='ppt' or fn[(j+1):]=='pptx'):
        print('your file is a MS Powerpoint file')
    elif(fn[(j+1):]=='py'):
        print('your file is a python file')
    elif(fn[(j+1):]=='java' or fn[(j+1):]=='class'):
        print('your file is a java file')
    elif(fn[(j+1):]=='c'):
        print('your file is a c program file')
    elif(fn[(j+1):]=='pdf'):
        print('your file is a pdf file')
    elif(fn[(j+1):]=='xls'):
        print('your file is a MS Excel file')
    elif(fn[(j+1):]=='zip'):
        print('your file is a PC Zip Compressed Archive')
    else:
        print('enter correct file name along with extension')
if(type==2):
    str = input("enter the file names seperated by comma : ")
    arr  = str.split(",")
    exe=[]
    doc=[]
    html=[]
    ppt=[]
    py=[]
    java=[]
    c=[]
    pdf=[]
    xcel=[]
    zip1=[]
    for name in arr:
        le=len(name)
        for i in range(0,le):
            if(name[i]=='.'):
                j=i
        if(name[(j+1):]=='exe'):
            exe.append(name)
        elif(name[(j+1):]=='doc' or name=='docx'):
            doc.append(name)
        elif(name[(j+1):]=='html'):
            html.append(name)
        elif(name[(j+1):]=='ppt' or name[(j+1):]=='pptx'):
            ppt.append(name)
        elif(name[(j+1):]=='py'):
            py.append(name)
        elif(name[(j+1):]=='java' or name[(j+1):]=='class'):
            java.append(name)
        elif(name[(j+1):]=='c'):
            c.append(name)
        elif(name[(j+1):]=='pdf'):
            pdf.append(name)
        elif(name[(j+1):]=='xls'):
            xcel.append(name)
        elif(name[(j+1):]=='zip'):
            zip1.append(name)
        else:
            print('enter correct file with comma')
    print('1.Executabale')
    print('2.Ms word')
    print('3.html fle')
    print('4.powepoint')
    print('5.python file')
    print('6.java file')
    print('7.c file')
    print('8.pdffile')
    print('9.excel file')
    print('10.Zip compressed Archive')
    i=int(input('enter what type of file u want to classify (i.e., between 1 to 10): '))
    if(i==1):
        print("extension documents are",exe)
    elif(i==2):
        print("MS word documents are",doc)
    elif(i==3):
        print("html documents are",html)
    elif(i==4):
        print("MS Powerpoints are",ppt)
    elif(i==5):
        print("Python files are",py)
    elif(i==6):
        print("java documents are",java)
    elif(i==7):
        print("c files are",c)
    elif(i==8):
        print("pdf documents are",pdf)
    elif(i==9):
        print("MS Excel documents are",xcel)
    elif(i==10):
        print("Zip files are",zip1)